### ISSUE TITLE
Map too complex to generate

### ISSUE THREAD

**Issue by CupOHappiness** [julienvincent/cartographer#20]
Used this[ image ](https://imgur.com/DJuUZvE.png) to generate a map art.
8x8 
```
Failed to generate TypeError: Cannot read properties of undefined (reading '0')
    at t.and (48-5b2a45f65a7c3b66.js:1:15624)
    at t.set (48-5b2a45f65a7c3b66.js:1:15051)
    at 48-5b2a45f65a7c3b66.js:1:11611
    at Array.reduce (<anonymous>)
    at 48-5b2a45f65a7c3b66.js:1:11497
    at Array.reduce (<anonymous>)
    at 48-5b2a45f65a7c3b66.js:1:11458
    at Array.reduce (<anonymous>)
    at t.generateSchematicNBT (48-5b2a45f65a7c3b66.js:1:11419)
    at t.generateLitematicaSchema (48-5b2a45f65a7c3b66.js:1:4560)
```
Errored out.

**Comment by julienvincent** [comment]
Thanks for raising this. I haven't had much time to work on this in a while but I'll see if I can look into it this coming weekend.
